name: flutter_imagenetwork
description: A widget that loads a network image in flutter can set loading, progress, error, alt.
version: 0.6.2
homepage: https://github.com/januwA/flutter_package_imagenetwork

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: